import 'package:flutter/material.dart';

enum CharacterHairStyle {
  defaultMask,
  spikyShort,
  longPonytail,
  rangerCap,
  mageHood,
  frostBraid,
  knightHelmet,
  darkHorns,
  stormWings,
  celestialCrown,
  cyberGoggles,
  steampunkHat,
  ninjaBandana,
  pirateTricorn,
  samuraiTopknot,
  wildAfro,
  scoutBeret,
  vampireCollar,
  solarHalo,
  dragonHorns,
}

enum CharacterWeaponStyle {
  shortSword,
  rangerDagger,
  arcaneStaff,
  iceBlade,
  darkClaymore,
  stormSpear,
  celestialScepter,
  dualKatana,
  shadowScythe,
  fireAxe,
  plasmaBlaster,
  goldenBow,
  elementalOrb,
  runicMace,
}

enum CharacterAuraStyle {
  none,
  greenLeaves,
  shadowMist,
  arcaneGlow,
  frostFlakes,
  darkFlames,
  lightningSparks,
  celestialGold,
  plasmaRings,
  cherryBlossoms,
  emberSparks,
}

class CharacterData {
  final String id;
  final String name;
  final String gender;
  final String outfitTitle;
  final String description;
  final int price;
  final CharacterHairStyle hairStyle;
  final CharacterWeaponStyle weaponStyle;
  final CharacterAuraStyle auraStyle;

  final Color bodyColor;
  final Color cloakColor;
  final Color maskColor;
  final Color hairColor;
  final Color eyeColor;
  final Color eyeGlowColor;
  final Color weaponColor;
  final Color accentColor;

  const CharacterData({
    required this.id,
    required this.name,
    this.gender = 'Hero',
    required this.outfitTitle,
    required this.description,
    required this.price,
    required this.hairStyle,
    required this.weaponStyle,
    required this.auraStyle,
    required this.bodyColor,
    required this.cloakColor,
    required this.maskColor,
    required this.hairColor,
    required this.eyeColor,
    required this.eyeGlowColor,
    required this.weaponColor,
    required this.accentColor,
  });

  static const List<CharacterData> allCharacters = [
    // 1. Forest Adventurer (Default Free)
    CharacterData(
      id: 'char_1',
      name: 'Forest Adventurer',
      outfitTitle: 'Default Explorer',
      description: 'The brave woods explorer guided by forest magic.',
      price: 0,
      hairStyle: CharacterHairStyle.defaultMask,
      weaponStyle: CharacterWeaponStyle.shortSword,
      auraStyle: CharacterAuraStyle.none,
      bodyColor: Color(0xFFE2E8F0),
      cloakColor: Color(0xFF0EA5E9),
      maskColor: Color(0xFFFFFFFF),
      hairColor: Color(0xFF334155),
      eyeColor: Color(0xFF0F172A),
      eyeGlowColor: Color(0xFF80FFDB),
      weaponColor: Color(0xFFF1F5F9),
      accentColor: Color(0xFF0284C7),
    ),
    // 2. Verdant Vanguard
    CharacterData(
      id: 'char_2',
      name: 'Verdant Vanguard',
      outfitTitle: 'Mossy Warrior',
      description: 'Clad in elder bark armor infused with emerald leaf magic.',
      price: 150,
      hairStyle: CharacterHairStyle.spikyShort,
      weaponStyle: CharacterWeaponStyle.shortSword,
      auraStyle: CharacterAuraStyle.greenLeaves,
      bodyColor: Color(0xFF15803D),
      cloakColor: Color(0xFF166534),
      maskColor: Color(0xFFDCFCE7),
      hairColor: Color(0xFF854D0E),
      eyeColor: Color(0xFF052E16),
      eyeGlowColor: Color(0xFF4ADE80),
      weaponColor: Color(0xFF22C55E),
      accentColor: Color(0xFF15803D),
    ),
    // 3. Sylvan Scout
    CharacterData(
      id: 'char_3',
      name: 'Sylvan Scout',
      outfitTitle: 'Forest Ranger',
      description: 'Swift ranger adorned with a stylish cap and long ponytail.',
      price: 250,
      hairStyle: CharacterHairStyle.longPonytail,
      weaponStyle: CharacterWeaponStyle.rangerDagger,
      auraStyle: CharacterAuraStyle.greenLeaves,
      bodyColor: Color(0xFF047857),
      cloakColor: Color(0xFF065F46),
      maskColor: Color(0xFFFEF3C7),
      hairColor: Color(0xFFD97706),
      eyeColor: Color(0xFF064E3B),
      eyeGlowColor: Color(0xFF34D399),
      weaponColor: Color(0xFFF59E0B),
      accentColor: Color(0xFF10B981),
    ),
    // 4. Midnight Shinobi
    CharacterData(
      id: 'char_4',
      name: 'Midnight Shinobi',
      outfitTitle: 'Shadow Stalker',
      description: 'Veiled in obsidian smoke and purple phantom energy.',
      price: 350,
      hairStyle: CharacterHairStyle.ninjaBandana,
      weaponStyle: CharacterWeaponStyle.dualKatana,
      auraStyle: CharacterAuraStyle.shadowMist,
      bodyColor: Color(0xFF1E293B),
      cloakColor: Color(0xFF020617),
      maskColor: Color(0xFF334155),
      hairColor: Color(0xFF09090B),
      eyeColor: Color(0xFF581C87),
      eyeGlowColor: Color(0xFFA855F7),
      weaponColor: Color(0xFFC084FC),
      accentColor: Color(0xFF7E22CE),
    ),
    // 5. Mystic Sorceress
    CharacterData(
      id: 'char_5',
      name: 'Mystic Sorceress',
      outfitTitle: 'Arcane Mage',
      description: 'Master of incantations with a violet hood and magic staff.',
      price: 450,
      hairStyle: CharacterHairStyle.mageHood,
      weaponStyle: CharacterWeaponStyle.arcaneStaff,
      auraStyle: CharacterAuraStyle.arcaneGlow,
      bodyColor: Color(0xFF6B21A8),
      cloakColor: Color(0xFF4C1D95),
      maskColor: Color(0xFFEDE9FE),
      hairColor: Color(0xFFE879F9),
      eyeColor: Color(0xFF3B0764),
      eyeGlowColor: Color(0xFFF0ABFC),
      weaponColor: Color(0xFFE879F9),
      accentColor: Color(0xFF9333EA),
    ),
    // 6. Beast Hunter
    CharacterData(
      id: 'char_6',
      name: 'Beast Hunter',
      outfitTitle: 'Sylvan Tracker',
      description: 'Hardened tracker with leather vestments and amber hunting blades.',
      price: 550,
      hairStyle: CharacterHairStyle.rangerCap,
      weaponStyle: CharacterWeaponStyle.shortSword,
      auraStyle: CharacterAuraStyle.greenLeaves,
      bodyColor: Color(0xFF92400E),
      cloakColor: Color(0xFF78350F),
      maskColor: Color(0xFFFFE4E6),
      hairColor: Color(0xFF7C2D12),
      eyeColor: Color(0xFF451A03),
      eyeGlowColor: Color(0xFFFBBF24),
      weaponColor: Color(0xFFF59E0B),
      accentColor: Color(0xFFB45309),
    ),
    // 7. Glacial Valkyrie
    CharacterData(
      id: 'char_7',
      name: 'Glacial Valkyrie',
      outfitTitle: 'Frost Sentinel',
      description: 'Wielder of permafrost ice blades draped in snow braids.',
      price: 650,
      hairStyle: CharacterHairStyle.frostBraid,
      weaponStyle: CharacterWeaponStyle.iceBlade,
      auraStyle: CharacterAuraStyle.frostFlakes,
      bodyColor: Color(0xFF0284C7),
      cloakColor: Color(0xFF0369A1),
      maskColor: Color(0xFFE0F2FE),
      hairColor: Color(0xFFBAE6FD),
      eyeColor: Color(0xFF0C4A6E),
      eyeGlowColor: Color(0xFF38BDF8),
      weaponColor: Color(0xFF7DD3FC),
      accentColor: Color(0xFF0284C7),
    ),
    // 8. Abyssal Paladin
    CharacterData(
      id: 'char_8',
      name: 'Abyssal Paladin',
      outfitTitle: 'Dark Knight',
      description: 'Encased in heavy dark iron armor with glowing crimson visor.',
      price: 750,
      hairStyle: CharacterHairStyle.knightHelmet,
      weaponStyle: CharacterWeaponStyle.darkClaymore,
      auraStyle: CharacterAuraStyle.darkFlames,
      bodyColor: Color(0xFF18181B),
      cloakColor: Color(0xFF881337),
      maskColor: Color(0xFF27272A),
      hairColor: Color(0xFF09090B),
      eyeColor: Color(0xFF450A0A),
      eyeGlowColor: Color(0xFFEF4444),
      weaponColor: Color(0xFFF87171),
      accentColor: Color(0xFFDC2626),
    ),
    // 9. Thunder Sovereign
    CharacterData(
      id: 'char_9',
      name: 'Thunder Sovereign',
      outfitTitle: 'Storm Valkyrie',
      description: 'Winged sky warrior harnessing raw electric lightning.',
      price: 850,
      hairStyle: CharacterHairStyle.stormWings,
      weaponStyle: CharacterWeaponStyle.stormSpear,
      auraStyle: CharacterAuraStyle.lightningSparks,
      bodyColor: Color(0xFF1E1B4B),
      cloakColor: Color(0xFF312E81),
      maskColor: Color(0xFFEEF2FF),
      hairColor: Color(0xFFFDE047),
      eyeColor: Color(0xFF1E3A8A),
      eyeGlowColor: Color(0xFF60A5FA),
      weaponColor: Color(0xFFFACC15),
      accentColor: Color(0xFF3B82F6),
    ),
    // 10. Astral Monarch
    CharacterData(
      id: 'char_10',
      name: 'Astral Monarch',
      outfitTitle: 'Celestial Champion',
      description: 'Crowned in divine starlight and golden celestial magic.',
      price: 1000,
      hairStyle: CharacterHairStyle.celestialCrown,
      weaponStyle: CharacterWeaponStyle.celestialScepter,
      auraStyle: CharacterAuraStyle.celestialGold,
      bodyColor: Color(0xFF713F12),
      cloakColor: Color(0xFF854D0E),
      maskColor: Color(0xFFFEF9C3),
      hairColor: Color(0xFFFEF08A),
      eyeColor: Color(0xFF422006),
      eyeGlowColor: Color(0xFFFACC15),
      weaponColor: Color(0xFFFEF08A),
      accentColor: Color(0xFFEAB308),
    ),
    // 11. Cyber Rogue
    CharacterData(
      id: 'char_11',
      name: 'Cyber Rogue',
      outfitTitle: 'Neon Mercenary',
      description: 'Futuristic runner equipped with glowing cybernetic visor and plasma blades.',
      price: 1100,
      hairStyle: CharacterHairStyle.cyberGoggles,
      weaponStyle: CharacterWeaponStyle.plasmaBlaster,
      auraStyle: CharacterAuraStyle.plasmaRings,
      bodyColor: Color(0xFF0F172A),
      cloakColor: Color(0xFF0284C7),
      maskColor: Color(0xFF1E293B),
      hairColor: Color(0xFF38BDF8),
      eyeColor: Color(0xFF0284C7),
      eyeGlowColor: Color(0xFF38BDF8),
      weaponColor: Color(0xFF38BDF8),
      accentColor: Color(0xFF0EA5E9),
    ),
    // 12. Ember Samurai
    CharacterData(
      id: 'char_12',
      name: 'Ember Samurai',
      outfitTitle: 'Ronin of Flames',
      description: 'Master swordsman wielding flaming katanas and fiery topknot crest.',
      price: 1200,
      hairStyle: CharacterHairStyle.samuraiTopknot,
      weaponStyle: CharacterWeaponStyle.dualKatana,
      auraStyle: CharacterAuraStyle.emberSparks,
      bodyColor: Color(0xFF450A0A),
      cloakColor: Color(0xFF7F1D1D),
      maskColor: Color(0xFF991B1B),
      hairColor: Color(0xFFF97316),
      eyeColor: Color(0xFF7F1D1D),
      eyeGlowColor: Color(0xFFF97316),
      weaponColor: Color(0xFFF97316),
      accentColor: Color(0xFFDC2626),
    ),
    // 13. Solar Templar
    CharacterData(
      id: 'char_13',
      name: 'Solar Templar',
      outfitTitle: 'Sun Guardian',
      description: 'Radiant knight radiating a blinding golden solar halo.',
      price: 1300,
      hairStyle: CharacterHairStyle.solarHalo,
      weaponStyle: CharacterWeaponStyle.runicMace,
      auraStyle: CharacterAuraStyle.celestialGold,
      bodyColor: Color(0xFF78350F),
      cloakColor: Color(0xFFB45309),
      maskColor: Color(0xFFFEF3C7),
      hairColor: Color(0xFFFBBF24),
      eyeColor: Color(0xFF78350F),
      eyeGlowColor: Color(0xFFFACC15),
      weaponColor: Color(0xFFFBBF24),
      accentColor: Color(0xFFD97706),
    ),
    // 14. Poison Assassin
    CharacterData(
      id: 'char_14',
      name: 'Poison Assassin',
      outfitTitle: 'Venomous Phantom',
      description: 'Lethal ninja coated in toxic green mist and venom daggers.',
      price: 1400,
      hairStyle: CharacterHairStyle.ninjaBandana,
      weaponStyle: CharacterWeaponStyle.rangerDagger,
      auraStyle: CharacterAuraStyle.greenLeaves,
      bodyColor: Color(0xFF064E3B),
      cloakColor: Color(0xFF022C22),
      maskColor: Color(0xFF065F46),
      hairColor: Color(0xFF10B981),
      eyeColor: Color(0xFF022C22),
      eyeGlowColor: Color(0xFF34D399),
      weaponColor: Color(0xFF34D399),
      accentColor: Color(0xFF059669),
    ),
    // 15. Steampunk Engineer
    CharacterData(
      id: 'char_15',
      name: 'Steampunk Engineer',
      outfitTitle: 'Brass Alchemist',
      description: 'Inventor wearing brass goggles and a classic top hat.',
      price: 1500,
      hairStyle: CharacterHairStyle.steampunkHat,
      weaponStyle: CharacterWeaponStyle.plasmaBlaster,
      auraStyle: CharacterAuraStyle.none,
      bodyColor: Color(0xFF78350F),
      cloakColor: Color(0xFF451A03),
      maskColor: Color(0xFFD97706),
      hairColor: Color(0xFFB45309),
      eyeColor: Color(0xFF451A03),
      eyeGlowColor: Color(0xFFFBBF24),
      weaponColor: Color(0xFFF59E0B),
      accentColor: Color(0xFF92400E),
    ),
    // 16. Reaper Lord
    CharacterData(
      id: 'char_16',
      name: 'Reaper Lord',
      outfitTitle: 'Soul Harvester',
      description: 'Grim spectral entity wielding a dark phantom scythe.',
      price: 1600,
      hairStyle: CharacterHairStyle.darkHorns,
      weaponStyle: CharacterWeaponStyle.shadowScythe,
      auraStyle: CharacterAuraStyle.shadowMist,
      bodyColor: Color(0xFF09090B),
      cloakColor: Color(0xFF18181B),
      maskColor: Color(0xFF27272A),
      hairColor: Color(0xFF3F3F46),
      eyeColor: Color(0xFF09090B),
      eyeGlowColor: Color(0xFFA855F7),
      weaponColor: Color(0xFFC084FC),
      accentColor: Color(0xFF7E22CE),
    ),
    // 17. Phantom Pirate
    CharacterData(
      id: 'char_17',
      name: 'Phantom Pirate',
      outfitTitle: 'Corsair of the Deep',
      description: 'Swashbuckler with tricorn hat and glowing ethereal cutlass.',
      price: 1700,
      hairStyle: CharacterHairStyle.pirateTricorn,
      weaponStyle: CharacterWeaponStyle.shortSword,
      auraStyle: CharacterAuraStyle.arcaneGlow,
      bodyColor: Color(0xFF1E3A8A),
      cloakColor: Color(0xFF172554),
      maskColor: Color(0xFF1E40AF),
      hairColor: Color(0xFF60A5FA),
      eyeColor: Color(0xFF172554),
      eyeGlowColor: Color(0xFF93C5FD),
      weaponColor: Color(0xFF60A5FA),
      accentColor: Color(0xFF2563EB),
    ),
    // 18. Neon Specialist
    CharacterData(
      id: 'char_18',
      name: 'Neon Specialist',
      outfitTitle: 'Cyber Valkyrie',
      description: 'Agile operative in glowing magenta suit and energy blades.',
      price: 1800,
      hairStyle: CharacterHairStyle.cyberGoggles,
      weaponStyle: CharacterWeaponStyle.iceBlade,
      auraStyle: CharacterAuraStyle.plasmaRings,
      bodyColor: Color(0xFF831843),
      cloakColor: Color(0xFF500724),
      maskColor: Color(0xFF9F1239),
      hairColor: Color(0xFFF43F5E),
      eyeColor: Color(0xFF500724),
      eyeGlowColor: Color(0xFFFB7185),
      weaponColor: Color(0xFFF43F5E),
      accentColor: Color(0xFFE11D48),
    ),
    // 19. Lava Berserker
    CharacterData(
      id: 'char_19',
      name: 'Lava Berserker',
      outfitTitle: 'Magma Fiend',
      description: 'Fierce warrior forging heavy battleaxes out of molten rock.',
      price: 1900,
      hairStyle: CharacterHairStyle.dragonHorns,
      weaponStyle: CharacterWeaponStyle.fireAxe,
      auraStyle: CharacterAuraStyle.emberSparks,
      bodyColor: Color(0xFF7F1D1D),
      cloakColor: Color(0xFF450A0A),
      maskColor: Color(0xFF991B1B),
      hairColor: Color(0xFFF97316),
      eyeColor: Color(0xFF450A0A),
      eyeGlowColor: Color(0xFFF97316),
      weaponColor: Color(0xFFF97316),
      accentColor: Color(0xFFB91C1C),
    ),
    // 20. Void Warden
    CharacterData(
      id: 'char_20',
      name: 'Void Warden',
      outfitTitle: 'Ender Knight',
      description: 'Protector of the cosmic void wielding a star-forged claymore.',
      price: 2000,
      hairStyle: CharacterHairStyle.knightHelmet,
      weaponStyle: CharacterWeaponStyle.darkClaymore,
      auraStyle: CharacterAuraStyle.arcaneGlow,
      bodyColor: Color(0xFF311B92),
      cloakColor: Color(0xFF1A237E),
      maskColor: Color(0xFF4527A0),
      hairColor: Color(0xFF7C4DFF),
      eyeColor: Color(0xFF1A237E),
      eyeGlowColor: Color(0xFFB388FF),
      weaponColor: Color(0xFF7C4DFF),
      accentColor: Color(0xFF512DA8),
    ),
    // 21. Sakura Blade
    CharacterData(
      id: 'char_21',
      name: 'Sakura Blade',
      outfitTitle: 'Blossom Kunoichi',
      description: 'Graceful kunoichi surrounded by falling pink cherry blossoms.',
      price: 2100,
      hairStyle: CharacterHairStyle.longPonytail,
      weaponStyle: CharacterWeaponStyle.dualKatana,
      auraStyle: CharacterAuraStyle.cherryBlossoms,
      bodyColor: Color(0xFF9D174D),
      cloakColor: Color(0xFF701A75),
      maskColor: Color(0xFFFCE7F3),
      hairColor: Color(0xFFF472B6),
      eyeColor: Color(0xFF701A75),
      eyeGlowColor: Color(0xFFF472B6),
      weaponColor: Color(0xFFF472B6),
      accentColor: Color(0xFFDB2777),
    ),
    // 22. Ocean Sentinel
    CharacterData(
      id: 'char_22',
      name: 'Ocean Sentinel',
      outfitTitle: 'Tidal Guardian',
      description: 'Protector of the deep seas wielding a glowing blue spear.',
      price: 2200,
      hairStyle: CharacterHairStyle.stormWings,
      weaponStyle: CharacterWeaponStyle.stormSpear,
      auraStyle: CharacterAuraStyle.frostFlakes,
      bodyColor: Color(0xFF0F4C81),
      cloakColor: Color(0xFF0B2545),
      maskColor: Color(0xFF134074),
      hairColor: Color(0xFF38BDF8),
      eyeColor: Color(0xFF0B2545),
      eyeGlowColor: Color(0xFF38BDF8),
      weaponColor: Color(0xFF38BDF8),
      accentColor: Color(0xFF0284C7),
    ),
    // 23. Desert Nomad
    CharacterData(
      id: 'char_23',
      name: 'Desert Nomad',
      outfitTitle: 'Dune Wanderer',
      description: 'Wanderer of sun-scorched sands armed with golden curved blades.',
      price: 2300,
      hairStyle: CharacterHairStyle.scoutBeret,
      weaponStyle: CharacterWeaponStyle.goldenBow,
      auraStyle: CharacterAuraStyle.none,
      bodyColor: Color(0xFFB45309),
      cloakColor: Color(0xFF78350F),
      maskColor: Color(0xFFFDE68A),
      hairColor: Color(0xFFF59E0B),
      eyeColor: Color(0xFF78350F),
      eyeGlowColor: Color(0xFFFBBF24),
      weaponColor: Color(0xFFFBBF24),
      accentColor: Color(0xFFD97706),
    ),
    // 24. Rune Priest
    CharacterData(
      id: 'char_24',
      name: 'Rune Priest',
      outfitTitle: 'Elder Monk',
      description: 'Keeper of ancient runic knowledge wielding a glowing orb.',
      price: 2400,
      hairStyle: CharacterHairStyle.solarHalo,
      weaponStyle: CharacterWeaponStyle.elementalOrb,
      auraStyle: CharacterAuraStyle.arcaneGlow,
      bodyColor: Color(0xFF3730A3),
      cloakColor: Color(0xFF1E1B4B),
      maskColor: Color(0xFFE0E7FF),
      hairColor: Color(0xFF818CF8),
      eyeColor: Color(0xFF1E1B4B),
      eyeGlowColor: Color(0xFFA5B4FC),
      weaponColor: Color(0xFF818CF8),
      accentColor: Color(0xFF4F46E5),
    ),
    // 25. Stormbringer
    CharacterData(
      id: 'char_25',
      name: 'Stormbringer',
      outfitTitle: 'Tempest Lord',
      description: 'Commands fierce gales and crackling electric lightning.',
      price: 2500,
      hairStyle: CharacterHairStyle.spikyShort,
      weaponStyle: CharacterWeaponStyle.stormSpear,
      auraStyle: CharacterAuraStyle.lightningSparks,
      bodyColor: Color(0xFF1E1B4B),
      cloakColor: Color(0xFF312E81),
      maskColor: Color(0xFFC77DFF),
      hairColor: Color(0xFFE0AFA0),
      eyeColor: Color(0xFF1E1B4B),
      eyeGlowColor: Color(0xFFC77DFF),
      weaponColor: Color(0xFFC77DFF),
      accentColor: Color(0xFF7B2CBF),
    ),
    // 26. Emerald Druid
    CharacterData(
      id: 'char_26',
      name: 'Emerald Druid',
      outfitTitle: 'Wild Sage',
      description: 'Communes with nature and commands ancient overgrown vines.',
      price: 2600,
      hairStyle: CharacterHairStyle.wildAfro,
      weaponStyle: CharacterWeaponStyle.arcaneStaff,
      auraStyle: CharacterAuraStyle.greenLeaves,
      bodyColor: Color(0xFF14532D),
      cloakColor: Color(0xFF052E16),
      maskColor: Color(0xFF86EFAC),
      hairColor: Color(0xFF16A34A),
      eyeColor: Color(0xFF052E16),
      eyeGlowColor: Color(0xFF4ADE80),
      weaponColor: Color(0xFF22C55E),
      accentColor: Color(0xFF16A34A),
    ),
    // 27. Crimson Executioner
    CharacterData(
      id: 'char_27',
      name: 'Crimson Executioner',
      outfitTitle: 'Blood Blade',
      description: 'Feared duelist clad in crimson garb and razor scythe.',
      price: 2700,
      hairStyle: CharacterHairStyle.vampireCollar,
      weaponStyle: CharacterWeaponStyle.shadowScythe,
      auraStyle: CharacterAuraStyle.darkFlames,
      bodyColor: Color(0xFF881337),
      cloakColor: Color(0xFF4C0519),
      maskColor: Color(0xFFFDA4AF),
      hairColor: Color(0xFFFB7185),
      eyeColor: Color(0xFF4C0519),
      eyeGlowColor: Color(0xFFF43F5E),
      weaponColor: Color(0xFFF43F5E),
      accentColor: Color(0xFFE11D48),
    ),
    // 28. Frostbite Archer
    CharacterData(
      id: 'char_28',
      name: 'Frostbite Archer',
      outfitTitle: 'Ice Marksman',
      description: 'Shoots frozen ice arrows with deadly precision.',
      price: 2800,
      hairStyle: CharacterHairStyle.frostBraid,
      weaponStyle: CharacterWeaponStyle.goldenBow,
      auraStyle: CharacterAuraStyle.frostFlakes,
      bodyColor: Color(0xFF0369A1),
      cloakColor: Color(0xFF0C4A6E),
      maskColor: Color(0xFFE0F2FE),
      hairColor: Color(0xFF38BDF8),
      eyeColor: Color(0xFF0C4A6E),
      eyeGlowColor: Color(0xFF7DD3FC),
      weaponColor: Color(0xFF38BDF8),
      accentColor: Color(0xFF0284C7),
    ),
    // 29. Celestial Angel
    CharacterData(
      id: 'char_29',
      name: 'Celestial Angel',
      outfitTitle: 'Seraphim',
      description: 'Divine winged seraph shining with pure heavenly light.',
      price: 2900,
      hairStyle: CharacterHairStyle.stormWings,
      weaponStyle: CharacterWeaponStyle.celestialScepter,
      auraStyle: CharacterAuraStyle.celestialGold,
      bodyColor: Color(0xFFFAF5FF),
      cloakColor: Color(0xFFF3E8FF),
      maskColor: Color(0xFFFFFFFF),
      hairColor: Color(0xFFFDE047),
      eyeColor: Color(0xFF7E22CE),
      eyeGlowColor: Color(0xFFFACC15),
      weaponColor: Color(0xFFFACC15),
      accentColor: Color(0xFFEAB308),
    ),
    // 30. Titan Brawler
    CharacterData(
      id: 'char_30',
      name: 'Titan Brawler',
      outfitTitle: 'Stone Behemoth',
      description: 'Massive heavy brawler wielding an ancient stone mace.',
      price: 3000,
      hairStyle: CharacterHairStyle.knightHelmet,
      weaponStyle: CharacterWeaponStyle.runicMace,
      auraStyle: CharacterAuraStyle.none,
      bodyColor: Color(0xFF334155),
      cloakColor: Color(0xFF1E293B),
      maskColor: Color(0xFF64748B),
      hairColor: Color(0xFF475569),
      eyeColor: Color(0xFF0F172A),
      eyeGlowColor: Color(0xFF94A3B8),
      weaponColor: Color(0xFF94A3B8),
      accentColor: Color(0xFF475569),
    ),
    // 31. Shadow Blade
    CharacterData(
      id: 'char_31',
      name: 'Shadow Blade',
      outfitTitle: 'Void Assassin',
      description: 'Silent killer moving between shadows in an instant.',
      price: 3100,
      hairStyle: CharacterHairStyle.ninjaBandana,
      weaponStyle: CharacterWeaponStyle.shortSword,
      auraStyle: CharacterAuraStyle.shadowMist,
      bodyColor: Color(0xFF111827),
      cloakColor: Color(0xFF030712),
      maskColor: Color(0xFF374151),
      hairColor: Color(0xFF4B5563),
      eyeColor: Color(0xFF030712),
      eyeGlowColor: Color(0xFF9CA3AF),
      weaponColor: Color(0xFF9CA3AF),
      accentColor: Color(0xFF4B5563),
    ),
    // 32. Arcane Scholar
    CharacterData(
      id: 'char_32',
      name: 'Arcane Scholar',
      outfitTitle: 'Grand Wizard',
      description: 'Wears a ceremonial cowl and manipulates cosmic energy orbs.',
      price: 3200,
      hairStyle: CharacterHairStyle.mageHood,
      weaponStyle: CharacterWeaponStyle.elementalOrb,
      auraStyle: CharacterAuraStyle.arcaneGlow,
      bodyColor: Color(0xFF4338CA),
      cloakColor: Color(0xFF312E81),
      maskColor: Color(0xFFC7D2FE),
      hairColor: Color(0xFF818CF8),
      eyeColor: Color(0xFF312E81),
      eyeGlowColor: Color(0xFFA5B4FC),
      weaponColor: Color(0xFF818CF8),
      accentColor: Color(0xFF3730A3),
    ),
    // 33. Ironclad Juggernaut
    CharacterData(
      id: 'char_33',
      name: 'Ironclad Juggernaut',
      outfitTitle: 'Steel Fortress',
      description: 'An unstoppable wall of steel clad in reinforced plate armor.',
      price: 3300,
      hairStyle: CharacterHairStyle.knightHelmet,
      weaponStyle: CharacterWeaponStyle.fireAxe,
      auraStyle: CharacterAuraStyle.emberSparks,
      bodyColor: Color(0xFF27272A),
      cloakColor: Color(0xFF18181B),
      maskColor: Color(0xFF52525B),
      hairColor: Color(0xFF71717A),
      eyeColor: Color(0xFF18181B),
      eyeGlowColor: Color(0xFFF97316),
      weaponColor: Color(0xFFF97316),
      accentColor: Color(0xFFEA580C),
    ),
    // 34. Phoenix Guardian
    CharacterData(
      id: 'char_34',
      name: 'Phoenix Guardian',
      outfitTitle: 'Sunbird Knight',
      description: 'Reborn from ashes with flaming wings and golden armor.',
      price: 3400,
      hairStyle: CharacterHairStyle.solarHalo,
      weaponStyle: CharacterWeaponStyle.shortSword,
      auraStyle: CharacterAuraStyle.emberSparks,
      bodyColor: Color(0xFFC2410C),
      cloakColor: Color(0xFF7C2D12),
      maskColor: Color(0xFFFFEDD5),
      hairColor: Color(0xFFF97316),
      eyeColor: Color(0xFF7C2D12),
      eyeGlowColor: Color(0xFFFBBF24),
      weaponColor: Color(0xFFFBBF24),
      accentColor: Color(0xFFEA580C),
    ),
    // 35. Dragon Slayer
    CharacterData(
      id: 'char_35',
      name: 'Dragon Slayer',
      outfitTitle: 'Wyrm Hunter',
      description: 'Adorned in obsidian dragon scales with dragon horns.',
      price: 3500,
      hairStyle: CharacterHairStyle.dragonHorns,
      weaponStyle: CharacterWeaponStyle.darkClaymore,
      auraStyle: CharacterAuraStyle.darkFlames,
      bodyColor: Color(0xFF312E81),
      cloakColor: Color(0xFF1E1B4B),
      maskColor: Color(0xFF4338CA),
      hairColor: Color(0xFF818CF8),
      eyeColor: Color(0xFF1E1B4B),
      eyeGlowColor: Color(0xFFF43F5E),
      weaponColor: Color(0xFFF43F5E),
      accentColor: Color(0xFF3730A3),
    ),
    // 36. Quantum Sentinel
    CharacterData(
      id: 'char_36',
      name: 'Quantum Sentinel',
      outfitTitle: 'Chrono Operative',
      description: 'Futuristic temporal enforcer using plasma weaponry.',
      price: 3600,
      hairStyle: CharacterHairStyle.cyberGoggles,
      weaponStyle: CharacterWeaponStyle.plasmaBlaster,
      auraStyle: CharacterAuraStyle.plasmaRings,
      bodyColor: Color(0xFF0F766E),
      cloakColor: Color(0xFF134E4A),
      maskColor: Color(0xFFCCFBF1),
      hairColor: Color(0xFF2DD4BF),
      eyeColor: Color(0xFF134E4A),
      eyeGlowColor: Color(0xFF5EEAD4),
      weaponColor: Color(0xFF2DD4BF),
      accentColor: Color(0xFF0D9488),
    ),
    // 37. Valkyrie Queen
    CharacterData(
      id: 'char_37',
      name: 'Valkyrie Queen',
      outfitTitle: 'Sovereign Maiden',
      description: 'Ruler of the heavens adorned with silver winged helmet.',
      price: 3700,
      hairStyle: CharacterHairStyle.stormWings,
      weaponStyle: CharacterWeaponStyle.stormSpear,
      auraStyle: CharacterAuraStyle.celestialGold,
      bodyColor: Color(0xFF0369A1),
      cloakColor: Color(0xFF075985),
      maskColor: Color(0xFFE0F2FE),
      hairColor: Color(0xFFFDE047),
      eyeColor: Color(0xFF075985),
      eyeGlowColor: Color(0xFF38BDF8),
      weaponColor: Color(0xFFFACC15),
      accentColor: Color(0xFF0284C7),
    ),
    // 38. Eclipse Monk
    CharacterData(
      id: 'char_38',
      name: 'Eclipse Monk',
      outfitTitle: 'Twilight Sage',
      description: 'Balances light and dark magic in perfect harmony.',
      price: 3800,
      hairStyle: CharacterHairStyle.wildAfro,
      weaponStyle: CharacterWeaponStyle.elementalOrb,
      auraStyle: CharacterAuraStyle.shadowMist,
      bodyColor: Color(0xFF581C87),
      cloakColor: Color(0xFF3B0764),
      maskColor: Color(0xFFF3E8FF),
      hairColor: Color(0xFFC084FC),
      eyeColor: Color(0xFF3B0764),
      eyeGlowColor: Color(0xFFE879F9),
      weaponColor: Color(0xFFC084FC),
      accentColor: Color(0xFF7E22CE),
    ),
    // 39. Galactic Marshal
    CharacterData(
      id: 'char_39',
      name: 'Galactic Marshal',
      outfitTitle: 'Star Trooper',
      description: 'Space ranger in sleek white armor and blue visor.',
      price: 3900,
      hairStyle: CharacterHairStyle.cyberGoggles,
      weaponStyle: CharacterWeaponStyle.plasmaBlaster,
      auraStyle: CharacterAuraStyle.plasmaRings,
      bodyColor: Color(0xFF0284C7),
      cloakColor: Color(0xFF0369A1),
      maskColor: Color(0xFFF8FAFC),
      hairColor: Color(0xFF38BDF8),
      eyeColor: Color(0xFF0369A1),
      eyeGlowColor: Color(0xFF38BDF8),
      weaponColor: Color(0xFF38BDF8),
      accentColor: Color(0xFF0284C7),
    ),
    // 40. Nether Demon
    CharacterData(
      id: 'char_40',
      name: 'Nether Demon',
      outfitTitle: 'Underworld Lord',
      description: 'Fiendish overlord with dark horns and a scythe.',
      price: 4000,
      hairStyle: CharacterHairStyle.darkHorns,
      weaponStyle: CharacterWeaponStyle.shadowScythe,
      auraStyle: CharacterAuraStyle.darkFlames,
      bodyColor: Color(0xFF450A0A),
      cloakColor: Color(0xFF18181B),
      maskColor: Color(0xFF7F1D1D),
      hairColor: Color(0xFFEF4444),
      eyeColor: Color(0xFF18181B),
      eyeGlowColor: Color(0xFFEF4444),
      weaponColor: Color(0xFFEF4444),
      accentColor: Color(0xFF991B1B),
    ),
    // 41. Sunstone Nomad
    CharacterData(
      id: 'char_41',
      name: 'Sunstone Nomad',
      outfitTitle: 'Desert Shaman',
      description: 'Harnesses ancient solar gems and golden daggers.',
      price: 4100,
      hairStyle: CharacterHairStyle.scoutBeret,
      weaponStyle: CharacterWeaponStyle.goldenBow,
      auraStyle: CharacterAuraStyle.celestialGold,
      bodyColor: Color(0xFF9A3412),
      cloakColor: Color(0xFF7C2D12),
      maskColor: Color(0xFFFFEDD5),
      hairColor: Color(0xFFF97316),
      eyeColor: Color(0xFF7C2D12),
      eyeGlowColor: Color(0xFFFBBF24),
      weaponColor: Color(0xFFFBBF24),
      accentColor: Color(0xFFC2410C),
    ),
    // 42. Blizzard Knight
    CharacterData(
      id: 'char_42',
      name: 'Blizzard Knight',
      outfitTitle: 'Frost Paladin',
      description: 'Armored knight wielding an icy broadsword in freezing blizzards.',
      price: 4200,
      hairStyle: CharacterHairStyle.knightHelmet,
      weaponStyle: CharacterWeaponStyle.iceBlade,
      auraStyle: CharacterAuraStyle.frostFlakes,
      bodyColor: Color(0xFF0F4C81),
      cloakColor: Color(0xFF1E293B),
      maskColor: Color(0xFFE2E8F0),
      hairColor: Color(0xFF94A3B8),
      eyeColor: Color(0xFF0F172A),
      eyeGlowColor: Color(0xFF38BDF8),
      weaponColor: Color(0xFF7DD3FC),
      accentColor: Color(0xFF0284C7),
    ),
    // 43. Bio-Hazard Agent
    CharacterData(
      id: 'char_43',
      name: 'Bio-Hazard Agent',
      outfitTitle: 'Toxic Commando',
      description: 'Protective hazmat commando with glowing green visor.',
      price: 4300,
      hairStyle: CharacterHairStyle.cyberGoggles,
      weaponStyle: CharacterWeaponStyle.plasmaBlaster,
      auraStyle: CharacterAuraStyle.greenLeaves,
      bodyColor: Color(0xFF15803D),
      cloakColor: Color(0xFF14532D),
      maskColor: Color(0xFF22C55E),
      hairColor: Color(0xFF4ADE80),
      eyeColor: Color(0xFF14532D),
      eyeGlowColor: Color(0xFF4ADE80),
      weaponColor: Color(0xFF4ADE80),
      accentColor: Color(0xFF16A34A),
    ),
    // 44. High Elven Prince
    CharacterData(
      id: 'char_44',
      name: 'High Elven Prince',
      outfitTitle: 'Royal Noble',
      description: 'Noble elven warrior wearing golden crown and silk robes.',
      price: 4400,
      hairStyle: CharacterHairStyle.celestialCrown,
      weaponStyle: CharacterWeaponStyle.shortSword,
      auraStyle: CharacterAuraStyle.cherryBlossoms,
      bodyColor: Color(0xFF1E1B4B),
      cloakColor: Color(0xFF312E81),
      maskColor: Color(0xFFF3E8FF),
      hairColor: Color(0xFFFEF08A),
      eyeColor: Color(0xFF312E81),
      eyeGlowColor: Color(0xFFFACC15),
      weaponColor: Color(0xFFFACC15),
      accentColor: Color(0xFF4F46E5),
    ),
    // 45. Obsidian Warlock
    CharacterData(
      id: 'char_45',
      name: 'Obsidian Warlock',
      outfitTitle: 'Void Sorcerer',
      description: 'Dark sorcerer clad in black hood casting void spells.',
      price: 4500,
      hairStyle: CharacterHairStyle.mageHood,
      weaponStyle: CharacterWeaponStyle.arcaneStaff,
      auraStyle: CharacterAuraStyle.darkFlames,
      bodyColor: Color(0xFF18181B),
      cloakColor: Color(0xFF09090B),
      maskColor: Color(0xFF27272A),
      hairColor: Color(0xFFA855F7),
      eyeColor: Color(0xFF09090B),
      eyeGlowColor: Color(0xFFC084FC),
      weaponColor: Color(0xFFC084FC),
      accentColor: Color(0xFF7E22CE),
    ),
    // 46. Chrono Traveller
    CharacterData(
      id: 'char_46',
      name: 'Chrono Traveller',
      outfitTitle: 'Time Wanderer',
      description: 'Wanderer in leather coat manipulating time fragments.',
      price: 4600,
      hairStyle: CharacterHairStyle.steampunkHat,
      weaponStyle: CharacterWeaponStyle.elementalOrb,
      auraStyle: CharacterAuraStyle.plasmaRings,
      bodyColor: Color(0xFF0369A1),
      cloakColor: Color(0xFF075985),
      maskColor: Color(0xFFBAE6FD),
      hairColor: Color(0xFF38BDF8),
      eyeColor: Color(0xFF075985),
      eyeGlowColor: Color(0xFF7DD3FC),
      weaponColor: Color(0xFF38BDF8),
      accentColor: Color(0xFF0284C7),
    ),
    // 47. Valkyrie Maiden
    CharacterData(
      id: 'char_47',
      name: 'Valkyrie Maiden',
      outfitTitle: 'Sky Defender',
      description: 'Fair warrior maiden blessed with holy winged armor.',
      price: 4700,
      hairStyle: CharacterHairStyle.stormWings,
      weaponStyle: CharacterWeaponStyle.stormSpear,
      auraStyle: CharacterAuraStyle.lightningSparks,
      bodyColor: Color(0xFF0284C7),
      cloakColor: Color(0xFF0369A1),
      maskColor: Color(0xFFE0F2FE),
      hairColor: Color(0xFFFDE047),
      eyeColor: Color(0xFF0369A1),
      eyeGlowColor: Color(0xFF38BDF8),
      weaponColor: Color(0xFFFACC15),
      accentColor: Color(0xFF0284C7),
    ),
    // 48. Mythic Dragon
    CharacterData(
      id: 'char_48',
      name: 'Mythic Dragon',
      outfitTitle: 'Draconic Sovereign',
      description: 'Awakened dragon lord clad in fiery draconic scales.',
      price: 4800,
      hairStyle: CharacterHairStyle.dragonHorns,
      weaponStyle: CharacterWeaponStyle.fireAxe,
      auraStyle: CharacterAuraStyle.emberSparks,
      bodyColor: Color(0xFF991B1B),
      cloakColor: Color(0xFF7F1D1D),
      maskColor: Color(0xFFFCA5A5),
      hairColor: Color(0xFFF97316),
      eyeColor: Color(0xFF7F1D1D),
      eyeGlowColor: Color(0xFFFACC15),
      weaponColor: Color(0xFFF97316),
      accentColor: Color(0xFFDC2626),
    ),
    // 49. Celestial Empress
    CharacterData(
      id: 'char_49',
      name: 'Celestial Empress',
      outfitTitle: 'Astral Queen',
      description: 'Regal queen crowned with golden stars and starlight scepter.',
      price: 4900,
      hairStyle: CharacterHairStyle.celestialCrown,
      weaponStyle: CharacterWeaponStyle.celestialScepter,
      auraStyle: CharacterAuraStyle.celestialGold,
      bodyColor: Color(0xFF854D0E),
      cloakColor: Color(0xFF713F12),
      maskColor: Color(0xFFFEF08A),
      hairColor: Color(0xFFFACC15),
      eyeColor: Color(0xFF713F12),
      eyeGlowColor: Color(0xFFFEF08A),
      weaponColor: Color(0xFFFACC15),
      accentColor: Color(0xFFEAB308),
    ),
    // 50. Eternal Legend
    CharacterData(
      id: 'char_50',
      name: 'Eternal Legend',
      outfitTitle: 'Supreme Sovereign',
      description: 'The ultimate master of all elements, shining with eternal light.',
      price: 5000,
      hairStyle: CharacterHairStyle.solarHalo,
      weaponStyle: CharacterWeaponStyle.celestialScepter,
      auraStyle: CharacterAuraStyle.celestialGold,
      bodyColor: Color(0xFF0F172A),
      cloakColor: Color(0xFF0284C7),
      maskColor: Color(0xFF80FFDB),
      hairColor: Color(0xFFFDE047),
      eyeColor: Color(0xFF0F172A),
      eyeGlowColor: Color(0xFF80FFDB),
      weaponColor: Color(0xFF80FFDB),
      accentColor: Color(0xFF38BDF8),
    ),
  ];

  static CharacterData getById(String id) {
    return allCharacters.firstWhere(
      (c) => c.id == id,
      orElse: () => allCharacters.first,
    );
  }
}
