"""
MSAI Studio - AI Provider Abstraction
"""
import os
import json
import urllib.request
import urllib.error
from typing import Dict, Any, Tuple

class AIProvider:
    """Base interface and implementation for AI service integrations (e.g. Gemini, OpenAI, Mock)."""

    def __init__(self, api_key: str = None, model: str = "gemini-1.5-pro"):
        self.api_key = api_key or os.environ.get("GOOGLE_API_KEY", "")
        self.model = model

    def set_api_key(self, api_key: str):
        self.api_key = api_key

    def generate_response(self, prompt: str, system_instruction: str = "") -> Tuple[bool, str]:
        """Generates response using Gemini REST API or falls back gracefully."""
        if not self.api_key:
            return False, "AI API Key is missing. Please configure your API Key in Settings or set GOOGLE_API_KEY environment variable."

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"

        contents = []
        if system_instruction:
            contents.append({
                "role": "user",
                "parts": [{"text": f"System Instruction: {system_instruction}"}]
            })
        contents.append({
            "role": "user",
            "parts": [{"text": prompt}]
        })

        payload = {
            "contents": contents
        }

        try:
            req = urllib.request.Request(
                url,
                data=json.dumps(payload).encode("utf-8"),
                headers={"Content-Type": "application/json"},
                method="POST"
            )
            with urllib.request.urlopen(req, timeout=15) as response:
                res_data = json.loads(response.read().decode("utf-8"))
                candidates = res_data.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        return True, parts[0].get("text", "").strip()
                return False, "No response generated by AI model."
        except urllib.error.HTTPError as e:
            return False, f"AI Request HTTP Error {e.code}: {e.reason}"
        except Exception as e:
            return False, f"AI Request failed: {e}"
